services:
    mongo-rs-1-1:
        container_name: "mongo-1-1"
        image: mongobuild
        ports:
            - "30201:27017"
        command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
        links:
            - mongo-rs-1-2:mongo-rs-1-2
            - mongo-rs-1-3:mongo-rs-1-3
        restart: "always

     mongo-rs-1-2:
          container_name:"mongo-rs-1-2"
          image: mongobuild
          ports:
               - "30202:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-3:
          container_name:"mongo-rs-1-3"
          image: mongobuild
          ports:
               - "30203:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-4:
          container_name:"mongo-rs-1-4"
          image: mongobuild
          ports:
               - "30204:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-5:
          container_name:"mongo-rs-1-5"
          image: mongobuild
          ports:
               - "30205:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-6:
          container_name:"mongo-rs-1-6"
          image: mongobuild
          ports:
               - "30206:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-7:
          container_name:"mongo-rs-1-7"
          image: mongobuild
          ports:
               - "30207:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-8:
          container_name:"mongo-rs-1-8"
          image: mongobuild
          ports:
               - "30208:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-9:
          container_name:"mongo-rs-1-9"
          image: mongobuild
          ports:
               - "30209:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-10:
          container_name:"mongo-rs-1-10"
          image: mongobuild
          ports:
               - "30210:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-11:
          container_name:"mongo-rs-1-11"
          image: mongobuild
          ports:
               - "30211:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-12:
          container_name:"mongo-rs-1-12"
          image: mongobuild
          ports:
               - "30212:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-13:
          container_name:"mongo-rs-1-13"
          image: mongobuild
          ports:
               - "30213:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-14:
          container_name:"mongo-rs-1-14"
          image: mongobuild
          ports:
               - "30214:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-15:
          container_name:"mongo-rs-1-15"
          image: mongobuild
          ports:
               - "30215:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-16:
          container_name:"mongo-rs-1-16"
          image: mongobuild
          ports:
               - "30216:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-17:
          container_name:"mongo-rs-1-17"
          image: mongobuild
          ports:
               - "30217:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-18:
          container_name:"mongo-rs-1-18"
          image: mongobuild
          ports:
               - "30218:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-19:
          container_name:"mongo-rs-1-19"
          image: mongobuild
          ports:
               - "30219:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-20:
          container_name:"mongo-rs-1-20"
          image: mongobuild
          ports:
               - "30220:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-21:
          container_name:"mongo-rs-1-21"
          image: mongobuild
          ports:
               - "30221:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-22:
          container_name:"mongo-rs-1-22"
          image: mongobuild
          ports:
               - "30222:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-23:
          container_name:"mongo-rs-1-23"
          image: mongobuild
          ports:
               - "30223:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-24:
          container_name:"mongo-rs-1-24"
          image: mongobuild
          ports:
               - "30224:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"



     mongo-rs-1-25:
          container_name:"mongo-rs-1-25"
          image: mongobuild
          ports:
               - "30225:27017"
          command: mongod --replSet rs-1 --port 27017 --nojournal --oplogSize 16 --noprealloc --smallfiles
          restart: "always"

    mongo-rs-1-setup:
        container_name: "mongo-rs-1-setup"
        image: mongobuild
        depends_on:
            - "mongo-rs-1-1"
            - "mongo-rs-1-2"
            - "mongo-rs-1-3"
            - "mongo-rs-1-4"
            - "mongo-rs-1-5"
            - "mongo-rs-1-6"
            - "mongo-rs-1-7"
            - "mongo-rs-1-8"
            - "mongo-rs-1-9"
            - "mongo-rs-1-10"
            - "mongo-rs-1-11"
            - "mongo-rs-1-12"
            - "mongo-rs-1-13"
            - "mongo-rs-1-14"
            - "mongo-rs-1-15"
            - "mongo-rs-1-16"
            - "mongo-rs-1-17"
            - "mongo-rs-1-18"
            - "mongo-rs-1-19"
            - "mongo-rs-1-20"
            - "mongo-rs-1-21"
            - "mongo-rs-1-22"
            - "mongo-rs-1-23"
            - "mongo-rs-1-24"
            - "mongo-rs-1-25"

        links:
            - mongo-rs-1-1:mongo-rs-1-1
            - mongo-rs-1-2:mongo-rs-1-2
            - mongo-rs-1-3:mongo-rs-1-3
            - mongo-rs-1-4:mongo-rs-1-4
            - mongo-rs-1-5:mongo-rs-1-5
            - mongo-rs-1-6:mongo-rs-1-6
            - mongo-rs-1-7:mongo-rs-1-7
            - mongo-rs-1-8:mongo-rs-1-8
            - mongo-rs-1-9:mongo-rs-1-9
            - mongo-rs-1-10:mongo-rs-1-10
            - mongo-rs-1-11:mongo-rs-1-11
            - mongo-rs-1-12:mongo-rs-1-12
            - mongo-rs-1-13:mongo-rs-1-13
            - mongo-rs-1-14:mongo-rs-1-14
            - mongo-rs-1-15:mongo-rs-1-15
            - mongo-rs-1-16:mongo-rs-1-16
            - mongo-rs-1-17:mongo-rs-1-17
            - mongo-rs-1-18:mongo-rs-1-18
            - mongo-rs-1-19:mongo-rs-1-19
            - mongo-rs-1-20:mongo-rs-1-20
            - mongo-rs-1-21:mongo-rs-1-21
            - mongo-rs-1-22:mongo-rs-1-22
            - mongo-rs-1-23:mongo-rs-1-23
            - mongo-rs-1-24:mongo-rs-1-24
            - mongo-rs-1-25:mongo-rs-1-25
        volumes:
            - ./replication:/replication
        environment:
            - MONGO1=mongo-rs-1-1
            - MONGO2=mongo-rs-1-2
            - MONGO3=mongo-rs-1-3
            - MONGO4=mongo-rs-1-4
            - MONGO5=mongo-rs-1-5
            - MONGO6=mongo-rs-1-6
            - MONGO7=mongo-rs-1-7
            - MONGO8=mongo-rs-1-8
            - MONGO9=mongo-rs-1-9
            - MONGO10=mongo-rs-1-10
            - MONGO11=mongo-rs-1-11
            - MONGO12=mongo-rs-1-12
            - MONGO13=mongo-rs-1-13
            - MONGO14=mongo-rs-1-14
            - MONGO15=mongo-rs-1-15
            - MONGO16=mongo-rs-1-16
            - MONGO17=mongo-rs-1-17
            - MONGO18=mongo-rs-1-18
            - MONGO19=mongo-rs-1-19
            - MONGO20=mongo-rs-1-20
            - MONGO21=mongo-rs-1-21
            - MONGO22=mongo-rs-1-22
            - MONGO23=mongo-rs-1-23
            - MONGO24=mongo-rs-1-24
            - MONGO25=mongo-rs-1-25

        entrypoint: [ "/replication/setup-rs-25.sh" ]"